import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";

import { Toaster } from "@/Components/ui/sonner";
import { PollContextProvider } from "@/Context/PollContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Poll Widget App",
  description: "Generated by Ujjwal Pandey",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + "min-h-screen bg-gray-900"}>
        <PollContextProvider>
          <Navbar />
          <div>{children}</div>
          <Toaster />
        </PollContextProvider>
      </body>
    </html>
  );
}
